import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/');
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await page.locator('[data-test="username"]').press('Tab');
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.locator('[data-test="password"]').press('Enter');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowRight');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowDown');
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('ArrowUp');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('ArrowLeft');
  await page.locator('body').press('Tab');
  await page.getByRole('button', { name: 'Open Menu' }).press('Enter');
  await page.getByRole('link', { name: 'All Items' }).press('ArrowDown');
  await page.getByRole('link', { name: 'About' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Logout' }).press('ArrowUp');
  await page.getByRole('link', { name: 'About' }).press('Enter');
  await page.getByLabel('Cookie banner').press('ArrowLeft');
  await page.goto('https://www.saucedemo.com/inventory.html');
  await page.goto('https://www.saucedemo.com/?/inventory.html');
  await page.goto('https://www.saucedemo.com/inventory.html');
  await page.getByRole('link', { name: 'About' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Logout' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Reset App State' }).press('ArrowDown');
  await page.getByRole('button', { name: 'Close Menu' }).press('ArrowDown');
  await page.getByRole('link', { name: 'All Items' }).press('ArrowUp');
  await page.getByRole('button', { name: 'Close Menu' }).press('ArrowUp');
  await page.getByRole('link', { name: 'Reset App State' }).press('ArrowUp');
  await page.getByRole('link', { name: 'Logout' }).press('Enter');
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await page.locator('[data-test="username"]').press('Tab');
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await page.locator('[data-test="password"]').press('Enter');
  await page.locator('body').press('Tab');
  await page.getByRole('button', { name: 'Open Menu' }).press('Enter');
  await page.getByRole('link', { name: 'All Items' }).press('ArrowDown');
  await page.getByRole('link', { name: 'About' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Logout' }).press('ArrowDown');
  await page.getByRole('link', { name: 'Reset App State' }).press('Enter');
  await page.getByRole('link', { name: 'Reset App State' }).press('ArrowUp');
  await page.getByRole('link', { name: 'Logout' }).press('ArrowUp');
  await page.getByRole('link', { name: 'About' }).press('Enter');
  await page.goto('https://www.saucedemo.com/inventory.html');
  await page.goto('https://www.saucedemo.com/?/inventory.html');
  await page.goto('https://www.saucedemo.com/inventory.html');
  await page.getByRole('link', { name: 'Logout' }).press('Enter');
});